### ISSUE TITLE
Jump back to previous line

### ISSUE THREAD

**Issue by madorian** [blue0513/point-history#19]
Is there any way to directly jump back to the previous line?

I don't want to first open the menu. 

I want to just jump backwards in point history;)

**Comment by madorian** [comment]
Ref this: 

https://emacs.stackexchange.com/questions/81157/how-can-i-go-directly-to-the-previous-line-with-point-history?noredirect=1#comment136351_81157

**Comment by blue0513** [comment]
Thank you so much for your interest in point-history and for taking the time to raise this issue.

At this moment, I'm not actively maintaining this project due to other commitments. However, I wholeheartedly welcome and support contributions from the community. If you feel inclined, I encourage you to submit a Pull Request to address this issue. I would be more than happy to review it and merge your changes.

Thank you again for your understanding and support.

**Comment by blue0513** [comment]
Altenatively, If you just want to back to the previous position where the cursor was, maybe you can use https://www.emacswiki.org/emacs/download/point-undo.el 👍 

Also this article (written in japanese) can help you: https://qiita.com/zk_phi/items/c145b7bd8077b8a0f537

**Comment by blue0513** [comment]
@madorian Thanks, I'll close this issue. If you have another question, please reopen this issue ✋
